### ISSUE TITLE
Cannot claim transaction with Thunderhub

### ISSUE THREAD

**Issue by taxmeifyoucan** [BoltzExchange/boltz-backend#226] opened 2020-12-13 10:38 UTC
Using Thunderhub via Btcpay docker latest version, I am not able to claim my swap. 
I see that transaction is `Ready to Claim` but when I try to claim it I get `ErrorCreatingClaimTransaction`. Thunderhub logs just repeat:
```
error [THUB]: Can not get vout or type from Boltz
```
Also worth mentioning, after paying the invoice, channel with Boltz looks like this:
![image](https://user-images.githubusercontent.com/61149543/102009371-4e3c4380-3d37-11eb-84ea-e21bc86afe6f.png)
Might be just UX issue but it is confusing, liquidity just disappeared and there is no remote balance.

**Comment by apotdevin** [comment] 2020-12-14 11:54
Hi! This seems to be some ThunderHub issue. What was your user flow? What did you click on?

**Comment by taxmeifyoucan** [comment] 2020-12-14 18:34
I opened Swap page, chose amount and Custom address, downloaded backup. Than paid with choosing Out Channel, after a while of waiting I refreshed and transaction was waiting for confirmation in Swap history. Then it changed to Ready to Claim and that's described above. 
Transaction was successfully refunded.

**Comment by michael1011** [comment] 2020-12-26 14:07
@taxmeifyoucan the issue should be fixed in the latest Thunderhub release: https://github.com/apotdevin/thunderhub/releases/tag/v0.12.2
Please try again and close this issue if you can't reproduce!

**Closed** 2021-03-19 13:35 UTC
